# Generated by Django 5.1.4 on 2025-01-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='surname',
            field=models.CharField(default='surname', max_length=255),
        ),
    ]
