# Generated by Django 5.1.4 on 2025-01-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_booking_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='surname',
        ),
    ]
